spring.application.name: user

server:
  port: 13001

spring:
  kafka:
    bootstrap-servers: localhost:9092

#hibernate:
#  hbm2ddl:
#    auto: create

jms:
  topic:
    user-lifecycle:
      creation: topic-user-lifecycle-creation
      update: topic-user-lifecycle-update