spring.application.name: user

server:
  port: 13001

spring:
  kafka:
    bootstrap-servers: kafka:9092

jms:
  topic:
    user-lifecycle:
      creation: topic-user-lifecycle-creation
      update: topic-user-lifecycle-update