version: '2'
services:
  gateway:
    image: meggot/oulipo/gateway:2.0-SNAPSHOT
    ports:
      - "13000:13000"
    environment:
      - "SPRING_PROFILES_ACTIVE=platformcompose"
  user:
    image: meggot/oulipo/user:2.0-SNAPSHOT
    ports:
      - "13001:13001"
    environment:
      - "SPRING_PROFILES_ACTIVE=platformcompose"
  project:
    image: meggot/oulipo/project:2.0-SNAPSHOT
    ports:
      - "13002:13002"
    environment:
      - "SPRING_PROFILES_ACTIVE=platformcompose"
  metadata:
    image: meggot/oulipo/metadata:2.0-SNAPSHOT
    ports:
      - "13003:13003"
    environment:
      - "SPRING_PROFILES_ACTIVE=platformcompose"
  audit:
    image: meggot/oulipo/audit:2.0-SNAPSHOT
    ports:
      - "13004:13004"
    environment:
      - "SPRING_PROFILES_ACTIVE=platformcompose"
  notify:
    image: meggot/oulipo/notify:2.0-SNAPSHOT
    ports:
      - "13005:13005"
    environment:
      - "SPRING_PROFILES_ACTIVE=platformcompose"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
