server:
  port: 13000

spring:
  application:
    name: gateway

zuul:
  routes:
    register:
      path: /register/
      url: http://localhost:13001/login/
    user:
      path: /users/**
      url: http://localhost:13001/
    project:
      path: /projects/**
      url: http://localhost:13002
      #serviceId: PROJECT-SERVICE
    metadata:
      path: /metadata/**
      url: http://localhost:13003/
    audit:
      path: /audit/**
      url: http://localhost:13004/
  host:
    socket-timeout-millis: 241000
    connect-timeout-millis: 241000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:13000/eureka/
  instance:
    prefer-ip-address: true

security:
  authentication:
    jwt:
      # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
      base64-secret: bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=
      # Token is valid 24 hours
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 2592000

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization,Link,X-Total-Count"
  allow-credentials: true
  max-age: 1800
