server:
  port:
    13005
spring:
  application:
    name: NOTIFY-SERVICE
  cloud:
    config:
      enabled: false
  kafka:
    bootstrap-servers: localhost:9092

jms:
  topic:
    user-lifecycle:
      creation: topic-user-lifecycle-creation
      update: topic-user-lifecycle-update
    project-lifecycle:
      creation: topic-project-lifecycle-creation
      update: topic-project-lifecycle-update