name: Destroy from Staging

on:
  push:
    branches: [ master ]

jobs:
  terraform:
    needs: build-backend
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Destroy'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'destroy'
          tf_actions_working_dir: './terraform'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
