# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Common Libraries
      run: ./common mvn -B install
    - name: Build Gateway service
      run: ./gateway mvn -B install dockerfile:build
    - name: Build Metadata service
      run: ./metadata mvn -B install dockerfile:build
    - name: Build Notify service
      run: ./notify mvn -B install dockerfile:build
    - name: Build Project service
      run: /project mvn -B install dockerfile:build
    - name: Build User service
      run: ./user mvn -B install dockerfile:build